server:
  port: 8081

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: # KHÔNG PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: "662fe9690ba83b"
    password: "ba28fabb8f56a6"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload-dir: "./uploads"

jwt:
  secret: "VGhpc0lzTXlTdXBlckxvbmdBbmRTZWN1cmVTZWNyZXRLZXlGb3JFY29tbWVyY2VQcm9qZWN0MjAyNQ=="
  expiration: 86400000

logging:
  level:
    com.nhom25.ecommerce: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

vnpay:
  tmnCode: "9WXOUA4B"
  hashSecret: "N6HX13PQHKAA7EY8LYCD3IJIJ3A2ZNI1"
  url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnUrlBase: "https://incompatibly-partakable-ileana.ngrok-free.dev/api/payments/vnpay_return"
  ipnUrlBase: "https://incompatibly-partakable-ileana.ngrok-free.dev/api/payments/vnpay_ipn"
